config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # get 'tasks', to: 'tasks#index', as: :tasks
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # post 'tasks', to: 'tasks#create'
  # get 'task/:id/edit', to: 'tasks#edit', as: :task_edit
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy', as: :task_delete
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show,:edit,:update,:destroy]
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_parameters)
    redirect_to tasks_path
  end

  def show
  end

  def edit
  end

  def update
    @task.update(task_parameters)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_parameters
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
  <%= form_for @task do |f| %>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class:"form-control" %>
    </div>
    <% if @task.new_record? %>
    <% else %>
    <div class="form-check-inline">
      <%= f.check_box :completed, class:"form-check-input"%>
      <%= f.label :completed, class:"form-check-label" %>
    </div>
    <%end %>
    <div class="sub">
    <%= f.submit :submit, class:"btn btn-danger btn-lg"%>
    </div>
  <% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Edit this task</h1>

    <%= render 'form', task: @task %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="wrapper">
  <div class="container">
    <h1>My Tasks</h1>
    <ul class="list-group-flush">
    <% @tasks.each do |task| %>
      <li class="list-group-item">
      <% if task.completed %>
      <i class="fas fa-check-square"></i>
      <% else %>
      <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task), class: 'linked' %>
      <%= link_to '', task_path(task), method: 'delete', class: 'fas fa-trash-alt linked', data: {confirm: "You Sure?"} %>
      </li>
    <% end %>
    </ul>
    <div>
      <%= link_to 'Create a new task', new_task_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Let's create a new task</h1>

    <%= render 'form', task: @task, class: "formed" %>

  </div>
</div>

app/views/tasks/show.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Task : <%=  @task.title %></h1>
    <p><%= @task.details%></p>
    <% if @task.completed %>
    <i class="fas fa-check-square"></i> <span>This task is completed</span>
      <% else %>
      <i class="far fa-square"></i> <span>This task is not completed yet</span>
    <% end %>
    <div class="edit">
      <%= link_to 'Edit this task', edit_task_path, class:"btn btn-danger btn-lg" %>
    </div>
    <div class="return">
    <%= link_to 'Return to tasks', tasks_path, class:"btn btn-primary btn-lg" %>
    </div>

  </div>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>